#!/usr/bin/env bash
# Install nginx

new_conf="server_name _;\n\rewrite ^/redirect_me/$ https://www.youtube.com/watch?v=9r1PPedJzng permanent;"

sudo apt update
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World" | sudo tee /var/www/html/index.html
sudo sed -i "s|server_name\ _;|$new_conf|" /etc/nginx/sites-available/default
sudo service nginx restart
