#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

apt-get -y update
apt-get -y upgrade
apt-get -y install haproxy
echo "
frontend http
	 bind *:80
	 mode http
	 default_backend web-backend
	 backend web-backend
balance roundrobin
	server 3457-web-01 35.229.85.201 check
	server 3457-web-02 34.202.237.164 check" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null
	service haproxy restart