#!/usr/bin/env bash
#for loop displaying Holberton School 10x
for ((iter = 0; iter < 10; iter++))
do
	echo "Best School"
done#!/usr/bin/env bash
# displays Holberton School 10 times

for _ in $(seq 1 10);
do
	echo "Holberton School"
done