#!/usr/bin/env bash
# Configure ufw so that it blocks all incoming traffic, except the TCP ports 22, 80, 443

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install ufw
sudo ufw disable
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw enable
© 2022 GitHub, Inc.